generator:
  class: sfPropelGenerator
  param:
    model_class:           Author
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          author
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:    
        display:    [id,username,email,location,homepageurl,plugins_count]
        
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
